### ISSUE TITLE
Menu: bene-subnav-breadcrumbs still showing up in subnav area

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#125]
## Overview
It looks like the `bene-subnav-breadcrumb` div is still showing up in the subnav area from time to time. 

![bene-subnav-breadcrumbs](https://user-images.githubusercontent.com/179803/30724227-71555600-9ef1-11e7-96ad-50f9fb3e9433.png)

**Comment by juliaford** [comment]
@tauno @heypaxton @mshaver Mike and I talked about this a bit this evening but how hard is it to enhance the user experience for the breadcrumbs so that you can see where you came from, and other child pages you could visit? Essentially mimicing the breadcrumb view that populates when you are on a parent page on the subpages (see SS #1) Also, if I am looking at "help people" which is a child of "what we do" "what we do" should be highlighted in purple on the main nav (see SS #2). 
#1: 
![screen shot 2017-09-21 at 7 35 48 pm](https://user-images.githubusercontent.com/28023410/30727114-1101c230-9f04-11e7-9af1-01275b5cd773.png)

#2: ![screen shot 2017-09-21 at 7 34 05 pm](https://user-images.githubusercontent.com/28023410/30727078-d5850d70-9f03-11e7-962b-08b6aea82b91.png)

**Comment by tauno** [comment]
The example in the original issue is from https://dev-frgk.pantheonsite.io/ways-give/donate-technology

The intent of the block is to show three things:
1. Breadcrumb excluding the current page - this is the unstyled item referenced above. `.bene-subnav-breadcrumbs`
1. Current page title `.bene-subnav-page-title`
1. List of child pages of the current page `.bene-subnav-children`

Is that what you're describing @juliaford?

**Comment by mshaver** [comment]
@juliaford I created a separate issue for the main nav active-trail styling: #124. It's possible that fixing the active-trail item in the main navigation will make the sub-nav issue below less important? 

@tauno, this might be more of a question for @vickibrown and how the subnav should operate. The problem seems to be that getting back to where you were is somewhat difficult. It seems like if we added the immediate parent of the child item, that would make it easier to move back up the hierarchy. I'll try to explain with an example:

### Hierarchy
- Main Nav Item: Ways To Give
  - Child Item: Donate
    - Child Item: Online
    - Child Item: Mail
       - Child Item: US Address
       - Child Item: International Address 
  - Child Item: Volunteer

### Sub Nav (bold = link)
- Ways To Give > **Donate** **Volunteer**
- **Ways To Give** > Donate > **Online** **Mail**
- **Donate** > Mail > **US Address** **International Address**

**Comment by vickibrown** [comment]
@mshaver That could work though it might be confusing. I think we were generally expecting that people could use the back button if the site starts getting really deep with content.

**Comment by tauno** [comment]
@mshaver I believe what you're describing is how it's built. Definitely possible it's not working as expected though - in particular caching could be giving us trouble.

**Comment by tauno** [comment]
This code is done for this. Assigned to @heypaxton for any base theming work that's needed.
