### ISSUE TITLE
WRI: ckeditor button styles not showing up in editor

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#169]
## Overview
The ckeditor button styles for WRI are not showing up in the WYSIWYG editor. 

![wri-button-styles.png](https://images.zenhubusercontent.com/53050d472ff23425210002b4/e95800cd-77d7-41ea-92e4-6292abfd037f)

**Comment by komejo** [comment]
Issue here: https://www.drupal.org/project/drupal/issues/2911749

Will be fixed in Drupal 8.5, currently set for March 7th release. There's a patch to the ckeditor library, but that seems like a bad idea. As a stopgap, we can advise clients to click the link, then the link highlight button on the bottom of the CKEditor. See screencap.

![ckeditor-workaround](https://user-images.githubusercontent.com/1668324/35711644-d659af6c-0772-11e8-88ca-e0a52061818e.gif)

**Comment by mshaver** [comment]
This is great @komejo. It looks like the class being applied to the button isn't right or we need to style the button is the only thing. Here is what the style is looking like: 
![report_card___willamette_river_initiative](https://user-images.githubusercontent.com/179803/35783844-6192c3dc-09c3-11e8-8b87-16de794d48c2.png)

It should look like this:
![home___willamette_river_initiative](https://user-images.githubusercontent.com/179803/35783845-69cd57c4-09c3-11e8-81e0-bcc5076b7ccf.png)

**Comment by komejo** [comment]
On test!

**Comment by mshaver** [comment]
So close! Just need the text style and color to match:
![wri-button](https://user-images.githubusercontent.com/179803/35833852-c17e9f5e-0a87-11e8-849c-a8339f4d17d4.png)

**Comment by komejo** [comment]
Fixed and on test: https://test-wri-bene.pantheonsite.io/report-card

**Comment by mshaver** [comment]
👍
