### ISSUE TITLE
Bene: Drupal Core Update

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#208]
## Overview
Core 8.6
Misc module updates
paragraphs security update

## This ticket is done when:
- [ ] item
- [ ] item

**Comment by unclegcb** [comment]
Bene RC 2.0.7 is ready for review on Streettrust, including core 8.6 and updates to a good collection of modules and libraries:
https://rc207-streettrust-bene.pantheonsite.io/

Also available for review on WRI:
https://rc207-wri-bene.pantheonsite.io/

If these look good, we can roll this release and get it up to client test sites.

**Comment by juliaford** [comment]
@mshaver please review WRI, I will do STTR.

**Comment by mshaver** [comment]
@unclegcb, I'm not sure if this is related to the RC, but when I tested creating a new page as the admin user, after saving the page there was no theme? Here is the page I was creating: https://rc207-wri-bene.pantheonsite.io/taaad-asdfads

When you visit that page as anonymous it shows up fine, but when logged in as admin, I get no theme at all.

**Comment by juliaford** [comment]
@unclegcb just seeing theming oddities on listing pages re: STTR. Check out the layout on:
https://rc207-streettrust-bene.pantheonsite.io/updates (so theming related)
and then I know we hid the sidebar on events but the images are rendering oddly:
<img width="1220" alt="screen shot 2019-01-24 at 9 56 40 am" src="https://user-images.githubusercontent.com/28023410/51698385-e489e380-1fbe-11e9-8da5-9c55596cae29.png">

But this is all happening on live so looks good.

**Comment by unclegcb** [comment]
I'm not seeing that: what browser are you using? page looks exactly the same as live for me.

**Comment by unclegcb** [comment]
Bene 2.0.7 has been released and applied to most sites. It is ready for client review. Since this is a major revision number update of Drupal 8, I recommend we issue an "assumed approval" opportunity for clients to review on test. Particularly, paragraphs was updated, as were google analytics and metatag. More listed here: https://www.drupal.org/project/bene/releases/8.x-2.07

Current status:

2.0.7 is available on Test, with a copy of live data as of today:
WRI
CORI
STTR

2.0.7 is available on Dev:
OTFO

No action taken, but the upstream is available:
FRGK

Note that Freegeek appears to have neglected the prior release. If they want to apply that release WITHOUT this one, it is possible but challenging.

**Comment by mshaver** [comment]
Messages sent to WRI, CORI, FRGK. Scheduled deploy of the WRI, CORI release is Feb 13 at 2:00pm PT.
