### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#64]
## Overview
Use media_entity and related modules to support re-use of media items.

#### Types
1. Image
1. Video (YouTube and Vimeo)
1. Document (pdf, txt, doc, etc)

Future possibilities:
1. Twitter (could include now if effort is minimal)
1. Instagram (could include now if effort is minimal)
1. Gallery (slick.js or similar)
1. Generic embed to support wider variety of 3rd-party tools

#### View modes
1. Default
1. Thumbnail
1. Embed (See #68)

Future
1. Gallery

## Dev [8 hrs]
- [x] Bundles:
  - [x] Image
  - [x] Video
  - [x] Document (txt, pdf, doc, docx)

## Theme [2 hrs] (6 hrs moved to #68)
- [ ] Polish admin view of media items.

## This ticket is done when:
- [x] Admin or Staff can add media (jpeg, png, PDF, videos)
- [x] View media on media admin page

**Comment by tauno** [comment]
Initial work in `64-media` branch / #78

**Comment by juliaford** [comment]
@tauno @mshaver @heypaxton from FGRK "I've been able to do YouTube embeds easily. However, when I try to embed any other sort of media using the URL (i.e. a Google calendar or map) I get an error message. For example, when trying to add our class calendar as a media block I get:

Could not match any bundles to input: 'https://calendar.google.com/calendar/embed?src=p3cbgpr03ofq2lngffkn333u20%40group.calendar.google.com&ctz=America/Los_Angeles'

The only place I'm able to add these other types of media is once again in the intro block, since I'm able to toggle to the source HTML and embed an iframe.

Is this functionality of embedding non-YouTube items as media still in-the-works?"

**Comment by mshaver** [comment]
Hi @juliaford, the embed will only work with video at the moment. There are ways of adding other embeds like instagram and twitter, but nothing exists to embed a google calendar. I do recall FRGK needing some ability to embed their calendars, which should be possible by enabling Full HTML for the Staff Admin role on the Rich Text paragraph type. I'd like @tauno to weigh in as well though, as introducing multiple text formats for certain roles can be problematic. The main reason why this can cause issues is that those text formats are permission based, so if a "Staff Admin" changes the format to "Full HTML" and then a "Staff" user needs to edit that page, they would be prevented from doing so. It gets very confusing for users.

**Comment by juliaford** [comment]
@tauno close this? Unsure what the final answer was here.

**Comment by tauno** [comment]
Yes, @mshaver's suggestion of using the Full HTML format where this is needed is the approach for now.

**Comment by tauno** [comment]
see #147
