### ISSUE TITLE
Homepage Hero

### ISSUE THREAD

**Issue by mshaver** [thinkshout/bene#67]
## Overview
Single use block

## Dev [6 hrs]
- [x] Create new single use block plugin in `bene_core`:  Home Page Feature
- [x] Fields:
  - [x] Lead (text)
  - [x] Title (text - required)
  - [x] Link (label and url)
  - [x] Background image (Entity reference to Media bundle Image) using media browser to select.
- [x] Set default display settings to order the fields. Background image will use picture background formatter that is in-progress.
- [x] Default placement on home page

## Theme [4 hrs]
- [x] Theme for each device size.
- [ ] Test with/without Lead and Link fields
- [ ] Background variations

## This ticket is done when:
- [ ] Admin or Staff can modify home page hero block, adding an image, text, links
- [ ] Hero looks good on all responsive design

**Comment by ruscoe** [comment]
Theming note: the background image is defined in a data attribute, so the wrapper div looks like this:

```
<fieldset data-background="http://bene.dev/sites/default/files/3317135_deedf0b6_0.jpg" id="bene-home-page-feature" class="js-form-item form-item js-form-wrapper form-wrapper">
```

Let me know if this needs to change.

**Comment by komejo** [comment]
Added initial theming.

**Comment by tauno** [comment]
New plan on the home page hero in order to allow the admin to create multiple home page heros and choose which one displays. They also don't need to use the block placement system.

- [x] Create a content block type for the home page hero - "Background Image Hero" perhaps?
- [x] Use the standard field system to define the necessary fields including the media reference.
  - [x] Lead (text)
  - [x] Title (text - required)
  - [x] Link (label and url)
  - [x] Background image (Entity reference to Media bundle Image) using media browser to select.
- [x] Use the picture background formatter to set the background image to a responsive image (see the Featured paragraph or header image on content for how it works).
- [x] Create (or re-purpose the existing home page hero) block that's always placed on the front page. This block has one field - an entityreference to select the content block (created in the first step) desired to be displayed on the home page.
