### ISSUE TITLE
Google Analytics 

### ISSUE THREAD

**Issue by juliaford** [thinkshout/bene#87]
## Overview
Enable google analytics 

## Dev [hrs]
- [ ] Enable module on install
- [ ] Set default settings

## This ticket is done when:
- [ ] Individual sites can add their GA id and have it tracked.

**Comment by juliaford** [comment]
@tauno @ruscoe this is something that both clients have asked for. Please walk me through the functionality and how to set it up so I can translate it to this doc: https://docs.google.com/document/d/1hUPZhT0qJtTMEqk1VpKOUOs-4go0F3L5XDfRyErb2mY/edit#

**Comment by tauno** [comment]
I'm doing a bit of research on the best approach for this. I'm considering if we should just include Google Tag Manager since that can be used to include the analytics snippet and MANY more tracking snippets as well as more custom stuff. It does add complexity that we would likely need to help most smaller organizations get set up on GTM more than we would on Google Analytics itself.

**Comment by tauno** [comment]
Sticking with simple for now and using the google_analytics module. It's enabled for both client sites but we'll need to add their specific property ID's pre-launch. I'll add that to a launch checklist.
